//! Asking GitHub about the pull requests our sessions opened.
//!
//! **One query per refresh, over `gh api graphql`.** `pr-linkage.md` settles
//! the transport: the host queries with the user's `gh` token, and `gh api
//! graphql` is "fine as the first implementation (no extra dep)". It is more
//! than fine here — the alternative is an HTTP+TLS stack in a crate that
//! deliberately has none (D-008), and letting `gh` make the request means the
//! token is never read into this process at all. `gh auth token` stays the
//! documented auth story (#16); this is the same login, one layer up.
//!
//! **Linked PRs only, on the refresh path.** The document names each `(owner,
//! name, number)` we have a row for, under an alias. Never
//! `repository.pullRequests(first: 30)` — that would list a coworker's PRs on
//! the user's board. The one query that is not about linkage is
//! [`mine_query`], and it is scoped by *authorship* rather than by repository:
//! `viewer.pullRequests` is the signed-in user's own, which is what the board
//! offers to sign in for.
//!
//! **Every value is a GraphQL variable.** Owner and repo names come out of a
//! git remote, which is a string a repository controls; interpolating one into
//! a query document is an injection. Aliases (`pr0`, `pr1`, …) are generated by
//! this module and are the only thing written into the document.
//!
//! **A partial answer is a partial success.** GraphQL answers `data` *and*
//! `errors` together: one repository the token cannot see does not invalidate
//! the other nine. Anything that parses is applied; anything that does not is
//! reported per row.

use serde_json::Value;

use super::super::repo::exec::{self, RunError};
use super::super::store::{
    PrSnapshot, CHECKS_FAILING, CHECKS_PASSING, CHECKS_RUNNING, STATUS_CLOSED, STATUS_DRAFT,
    STATUS_MERGED, STATUS_OPEN,
};

const GH: &str = "gh";

/// GitHub's own advice is serial-ish traffic; one document per refresh is one
/// request, and a slow network must not wedge the host's request thread.
const API_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(20);

/// How many PRs one document asks about. GraphQL costs points per node, and a
/// user with more linked PRs than this gets the oldest-polled ones next tick
/// rather than one enormous query that trips a secondary limit.
pub const BATCH: usize = 25;

/// The `(owner, name, number)` of one linked PR, as the query names it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrKey {
    pub owner: String,
    pub name: String,
    pub number: i64,
}

/// Why a refresh could not happen. Three cases and not one, for the reason
/// [`super::super::repo::gh::GhAuth`] gives: "GitHub is not connected" sends a
/// user who has never installed `gh` to a login page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FetchError {
    NotInstalled,
    /// `gh` ran and said no. Carries its own first line, which is the most
    /// useful sentence anyone has about the failure.
    Failed(String),
    TimedOut,
    /// `gh` succeeded and printed something that is not the answer.
    Unparseable(String),
}

impl FetchError {
    pub fn reason(&self) -> &'static str {
        match self {
            Self::NotInstalled => "gh_missing",
            Self::Failed(_) => "gh_failed",
            Self::TimedOut => "gh_timeout",
            Self::Unparseable(_) => "gh_unparseable",
        }
    }

    pub fn detail(&self) -> String {
        match self {
            Self::NotInstalled => "GitHub CLI (gh) is not installed.".to_string(),
            Self::Failed(detail) => detail.clone(),
            Self::TimedOut => format!("gh did not answer within {}s.", API_TIMEOUT.as_secs()),
            Self::Unparseable(detail) => detail.clone(),
        }
    }

    /// What the user can do about it, when there is anything.
    pub fn remedy(&self, host: &str) -> Option<String> {
        match self {
            Self::NotInstalled => Some("brew install gh".to_string()),
            // `gh` reports both a missing login and a revoked token as an HTTP
            // 401; either way the way out is the same login.
            Self::Failed(detail) if is_auth_failure(detail) => {
                Some(format!("gh auth login --hostname {host}"))
            }
            _ => None,
        }
    }
}

fn is_auth_failure(detail: &str) -> bool {
    let lower = detail.to_ascii_lowercase();
    lower.contains("401")
        || lower.contains("bad credentials")
        || lower.contains("not logged")
        || lower.contains("authentication")
}

/// The document plus the `-F name=value` arguments that fill it in.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Query {
    pub document: String,
    pub variables: Vec<(String, String)>,
}

/// Build one document covering every key, each under an alias `pr<i>`.
///
/// The fields are exactly what the prototype's row draws — title, diffstat,
/// head and base, draft flag, state, review decision — plus the checks rollup.
/// The rollup hangs off the last commit rather than off the pull request: that
/// is where GitHub's schema puts `statusCheckRollup`, and it is the path `gh pr
/// checks` itself walks. `pr-linkage.md` sketches it on `PullRequest`, which
/// does not resolve.
pub fn build_query(keys: &[PrKey]) -> Query {
    let mut params = Vec::new();
    let mut body = String::new();
    let mut variables = Vec::new();
    for (index, key) in keys.iter().enumerate() {
        params.push(format!(
            "$owner{index}: String!, $name{index}: String!, $number{index}: Int!"
        ));
        body.push_str(&format!(
            "  pr{index}: repository(owner: $owner{index}, name: $name{index}) {{ \
             pullRequest(number: $number{index}) {{ ...PrFields }} }}\n"
        ));
        variables.push((format!("owner{index}"), key.owner.clone()));
        variables.push((format!("name{index}"), key.name.clone()));
        variables.push((format!("number{index}"), key.number.to_string()));
    }
    let document = format!(
        "query({}) {{\n{}}}\n{}",
        params.join(", "),
        body,
        PR_FIELDS_FRAGMENT
    );
    Query {
        document,
        variables,
    }
}

/// How many of the user's own pull requests one `pr/mine` asks for.
///
/// Same reasoning as [`BATCH`], one step sharper: every node here drags a
/// check rollup behind it, and somebody with eighty open PRs wants the eighty
/// most recently touched far less than they want the page to draw.
pub const MINE_LIMIT: usize = 25;

/// Every open pull request the signed-in user wrote.
///
/// `viewer.pullRequests` and deliberately not `search(query: "is:pr is:open
/// author:@me")`: the search string would have to be built into the document
/// (a search query is not a variable this module would let through), `@me` is
/// a convenience of the search *UI* rather than a documented GraphQL literal,
/// and `viewer` needs neither — it is authorship, resolved from the token
/// itself. Nothing in this document comes from outside this file, so there is
/// nothing here to inject into.
pub fn mine_query() -> Query {
    let document = format!(
        "query {{\n\
        \x20 viewer {{\n\
        \x20   login\n\
        \x20   pullRequests(states: OPEN, first: {MINE_LIMIT}, \
        orderBy: {{field: UPDATED_AT, direction: DESC}}) {{\n\
        \x20     nodes {{ ...PrFields repository {{ nameWithOwner }} }}\n\
        \x20   }}\n\
        \x20 }}\n\
        }}\n{PR_FIELDS_FRAGMENT}"
    );
    Query {
        document,
        variables: Vec::new(),
    }
}

/// One of the viewer's pull requests: GitHub's answer, plus the two facts the
/// snapshot does not carry because a linked row already knew them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MinePr {
    /// `owner/name`, from `repository.nameWithOwner`.
    pub repo: String,
    pub number: i64,
    pub snapshot: PrSnapshot,
}

/// The viewer, and what they have open.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MineAnswer {
    /// GitHub's own name for the token holder — the account the board is
    /// showing. `None` only if GitHub answered without one.
    pub login: Option<String>,
    pub pull_requests: Vec<MinePr>,
}

/// Split one `viewer` response into rows.
///
/// A response with no `viewer` at all is a *failure* rather than an empty
/// board: that is what a bad token, a rate limit and an SSO block all look
/// like, and reporting them as "no pull requests" would tell a signed-out user
/// they have none. An empty `nodes` array is the opposite — a real, and
/// entirely ordinary, answer.
pub fn parse_mine(body: &Value) -> Result<MineAnswer, FetchError> {
    let Some(viewer) = body.get("data").and_then(|data| data.get("viewer")) else {
        let message = body
            .get("errors")
            .and_then(Value::as_array)
            .and_then(|errors| errors.first())
            .and_then(|error| error.get("message"))
            .and_then(Value::as_str)
            .unwrap_or("GitHub did not answer with a viewer.");
        return Err(FetchError::Failed(message.to_string()));
    };
    let nodes = viewer
        .get("pullRequests")
        .and_then(|prs| prs.get("nodes"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let pull_requests = nodes
        .iter()
        .filter_map(|node| {
            let repo = node
                .get("repository")
                .and_then(|repo| repo.get("nameWithOwner"))
                .and_then(Value::as_str)?;
            let number = node.get("number").and_then(Value::as_i64)?;
            Some(MinePr {
                repo: repo.to_string(),
                number,
                snapshot: snapshot(node),
            })
        })
        .collect();
    Ok(MineAnswer {
        login: viewer
            .get("login")
            .and_then(Value::as_str)
            .map(str::to_string),
        pull_requests,
    })
}

const PR_FIELDS_FRAGMENT: &str = "fragment PrFields on PullRequest {\n\
  number title url isDraft state\n\
  additions deletions changedFiles\n\
  headRefName baseRefName reviewDecision updatedAt\n\
  commits(last: 1) { nodes { commit { statusCheckRollup {\n\
    state\n\
    contexts(first: 30) { nodes {\n\
      __typename\n\
      ... on CheckRun { name status conclusion }\n\
      ... on StatusContext { context state }\n\
    } }\n\
  } } } }\n\
}\n";

/// Run the query through `gh` and hand back the parsed JSON body.
///
/// The document goes in argv, which is safe: it contains no user data — every
/// owner, name and number travels as a `-F` variable. Nothing here ever holds a
/// token; `gh` reads its own.
/// A DNS hostname, optionally with a port. Deliberately narrow: this becomes
/// `gh --hostname`, and anything outside this set is a value we did not mean
/// to send.
fn is_hostname(host: &str) -> bool {
    !host.is_empty()
        && host.len() <= 253
        && host.split(':').next().is_some_and(|name| {
            !name.is_empty()
                && !name.starts_with(['-', '.'])
                && !name.ends_with('.')
                && name
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-')
        })
        && host.matches(':').count() <= 1
        && host
            .split_once(':')
            .is_none_or(|(_, port)| !port.is_empty() && port.chars().all(|c| c.is_ascii_digit()))
}

/// GraphQL variable names are identifiers; we send only ones we wrote.
fn is_variable_name(name: &str) -> bool {
    !name.is_empty()
        && name.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// The values we send are repository owners, names and numbers. `@` would make
/// `gh` read a file; a leading `-` would make the value look like a flag.
fn is_variable_value(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 256
        && !value.starts_with(['@', '-'])
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | '/'))
}

pub fn fetch(host: &str, query: &Query) -> Result<Value, FetchError> {
    // `host` and the variable values reach here from a repository's `origin`
    // and from tool output an agent can influence, so they are checked before
    // they become argv rather than trusted for having come from git.
    //
    // The sharp edge is `gh`'s own syntax, not the shell: `-F name=@path`
    // makes gh READ THAT FILE and send it, so an agent that can put
    // `@/Users/me/.ssh/id_ed25519` into a value it controls can exfiltrate a
    // file through a request we make with the user's token. `@` is therefore
    // rejected outright — no variable we send ever legitimately starts with
    // one — and a leading `-` is rejected so a value cannot pose as a flag.
    if !is_hostname(host) {
        return Err(FetchError::Failed(format!("refusing hostname {host:?}")));
    }
    let mut args: Vec<String> = vec![
        "api".into(),
        "graphql".into(),
        "--hostname".into(),
        host.to_string(),
        "-f".into(),
        format!("query={}", query.document),
    ];
    for (name, value) in &query.variables {
        if !is_variable_name(name) || !is_variable_value(value) {
            return Err(FetchError::Failed(format!(
                "refusing GraphQL variable {name}={value:?}"
            )));
        }
        args.push("-F".into());
        args.push(format!("{name}={value}"));
    }
    let borrowed: Vec<&str> = args.iter().map(String::as_str).collect();
    let output = exec::run(GH, &borrowed, API_TIMEOUT).map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    // A GraphQL error comes back as exit 1 *with* a body; keep the body when
    // there is one, because "Could not resolve to a Repository" is a better
    // sentence than "gh exited 1".
    let body: Result<Value, _> = serde_json::from_str(&output.stdout);
    match body {
        Ok(value) => Ok(value),
        Err(_) if !output.ok() => Err(FetchError::Failed(first_line(&output.stderr))),
        Err(err) => Err(FetchError::Unparseable(err.to_string())),
    }
}

fn first_line(text: &str) -> String {
    text.trim()
        .lines()
        .next()
        .unwrap_or("gh failed")
        .trim()
        .to_string()
}

/// One key's answer: what GitHub said, or why it said nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PrAnswer {
    Found(Box<PrSnapshot>),
    /// The alias resolved to nothing — a repository the token cannot see, a PR
    /// that was hard-deleted, a transferred repo. Not an error for the refresh
    /// as a whole, and deliberately not a reason to unlink: a token that lost
    /// access this morning must not delete the user's board.
    Missing(String),
}

/// Split one response into one answer per key, in the order they were asked.
pub fn parse_response(body: &Value, keys: &[PrKey]) -> Vec<PrAnswer> {
    let data = body.get("data");
    let errors = body.get("errors").and_then(Value::as_array);
    keys.iter()
        .enumerate()
        .map(|(index, key)| {
            let alias = format!("pr{index}");
            let node = data
                .and_then(|data| data.get(&alias))
                .and_then(|repo| repo.get("pullRequest"));
            match node {
                Some(node) if !node.is_null() => PrAnswer::Found(Box::new(snapshot(node))),
                _ => PrAnswer::Missing(
                    error_for(errors, &alias)
                        .unwrap_or_else(|| format!("GitHub returned nothing for {}", key.number)),
                ),
            }
        })
        .collect()
}

fn error_for(errors: Option<&Vec<Value>>, alias: &str) -> Option<String> {
    let errors = errors?;
    for error in errors {
        let matches = error
            .get("path")
            .and_then(Value::as_array)
            .map(|path| path.iter().any(|part| part.as_str() == Some(alias)))
            .unwrap_or(false);
        if matches {
            return error
                .get("message")
                .and_then(Value::as_str)
                .map(str::to_string);
        }
    }
    // A document-level error (a bad token, a rate limit) has no path and
    // applies to every alias.
    errors
        .first()
        .and_then(|error| error.get("message"))
        .and_then(Value::as_str)
        .map(str::to_string)
}

/// One `PullRequest` node, mapped onto what the store and the row need.
pub fn snapshot(node: &Value) -> PrSnapshot {
    let state = node.get("state").and_then(Value::as_str).unwrap_or("OPEN");
    let draft = node
        .get("isDraft")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let contexts = rollup_contexts(node);
    let checks = checks_from_contexts(&contexts);
    PrSnapshot {
        title: node
            .get("title")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
        status: status_of(state, draft).to_string(),
        check_state: check_state(node, &checks),
        review_state: node
            .get("reviewDecision")
            .and_then(Value::as_str)
            .map(|decision| decision.to_ascii_lowercase()),
        head_ref: string_field(node, "headRefName"),
        base_ref: string_field(node, "baseRefName"),
        additions: number_field(node, "additions"),
        deletions: number_field(node, "deletions"),
        changed_files: number_field(node, "changedFiles"),
        checks_json: serde_json::to_string(&checks).unwrap_or_else(|_| "[]".to_string()),
        pr_updated_at: string_field(node, "updatedAt"),
        url: string_field(node, "url"),
    }
}

/// One row of the checks line.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct CheckView {
    pub label: String,
    /// `passing` | `running` | `failing`.
    pub state: String,
}

fn rollup_contexts(node: &Value) -> Vec<Value> {
    node.get("commits")
        .and_then(|commits| commits.get("nodes"))
        .and_then(Value::as_array)
        .and_then(|nodes| nodes.first())
        .and_then(|entry| entry.get("commit"))
        .and_then(|commit| commit.get("statusCheckRollup"))
        .and_then(|rollup| rollup.get("contexts"))
        .and_then(|contexts| contexts.get("nodes"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
}

fn rollup_state(node: &Value) -> Option<String> {
    node.get("commits")
        .and_then(|commits| commits.get("nodes"))
        .and_then(Value::as_array)
        .and_then(|nodes| nodes.first())
        .and_then(|entry| entry.get("commit"))
        .and_then(|commit| commit.get("statusCheckRollup"))
        .and_then(|rollup| rollup.get("state"))
        .and_then(Value::as_str)
        .map(str::to_string)
}

/// GitHub's `StatusState` for the whole commit, mapped to the three words the
/// row draws. Derived from the contexts when the rollup itself is absent — a
/// repository can report contexts with no rollup state, and a checks line with
/// a red tick beside "no checks" would be nonsense.
fn check_state(node: &Value, checks: &[CheckView]) -> Option<String> {
    if let Some(state) = rollup_state(node) {
        return Some(
            match state.as_str() {
                "SUCCESS" => CHECKS_PASSING,
                "PENDING" | "EXPECTED" => CHECKS_RUNNING,
                _ => CHECKS_FAILING,
            }
            .to_string(),
        );
    }
    if checks.is_empty() {
        // No checks configured. Not "checks passed" — nothing ran.
        return None;
    }
    Some(worst_of(checks).to_string())
}

/// Failing beats running beats passing: a PR with one red check is red, and one
/// still-running check is not yet reviewable.
fn worst_of(checks: &[CheckView]) -> &'static str {
    if checks.iter().any(|check| check.state == CHECKS_FAILING) {
        CHECKS_FAILING
    } else if checks.iter().any(|check| check.state == CHECKS_RUNNING) {
        CHECKS_RUNNING
    } else {
        CHECKS_PASSING
    }
}

/// `statusCheckRollup.contexts` is a union of `CheckRun` (Actions and friends)
/// and `StatusContext` (the older commit-status API). Both are drawn the same
/// way, so both are flattened here rather than in the renderer.
fn checks_from_contexts(contexts: &[Value]) -> Vec<CheckView> {
    contexts
        .iter()
        .filter_map(|context| {
            match context.get("__typename").and_then(Value::as_str) {
                Some("CheckRun") => Some(CheckView {
                    label: context
                        .get("name")
                        .and_then(Value::as_str)
                        .unwrap_or("check")
                        .to_string(),
                    state: check_run_state(context).to_string(),
                }),
                Some("StatusContext") => Some(CheckView {
                    label: context
                        .get("context")
                        .and_then(Value::as_str)
                        .unwrap_or("status")
                        .to_string(),
                    state: status_context_state(
                        context.get("state").and_then(Value::as_str).unwrap_or(""),
                    )
                    .to_string(),
                }),
                // A union member added after this was written. Skipping it
                // costs one line on the checks card; guessing at it would put a
                // green tick under a check nobody has looked at.
                _ => None,
            }
        })
        .collect()
}

/// A `CheckRun` reports a lifecycle *and* an outcome, and only the pair means
/// anything: `conclusion: null` on a completed run is a run still finishing,
/// and `SKIPPED` is not a failure.
fn check_run_state(context: &Value) -> &'static str {
    let status = context
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or("QUEUED");
    if status != "COMPLETED" {
        return CHECKS_RUNNING;
    }
    match context.get("conclusion").and_then(Value::as_str) {
        Some("SUCCESS") | Some("NEUTRAL") | Some("SKIPPED") => CHECKS_PASSING,
        Some(_) => CHECKS_FAILING,
        None => CHECKS_RUNNING,
    }
}

fn status_context_state(state: &str) -> &'static str {
    match state {
        "SUCCESS" => CHECKS_PASSING,
        "PENDING" | "EXPECTED" => CHECKS_RUNNING,
        _ => CHECKS_FAILING,
    }
}

/// `state` + `isDraft` collapse into the one word `thread_prs.status` holds.
/// A merged PR that was opened as a draft is merged, not a draft.
fn status_of(state: &str, draft: bool) -> &'static str {
    match state {
        "MERGED" => STATUS_MERGED,
        "CLOSED" => STATUS_CLOSED,
        _ if draft => STATUS_DRAFT,
        _ => STATUS_OPEN,
    }
}

fn string_field(node: &Value, field: &str) -> Option<String> {
    node.get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

fn number_field(node: &Value, field: &str) -> i64 {
    node.get(field).and_then(Value::as_i64).unwrap_or(0)
}

// ---- `gh pr view`, the post-turn fallback ------------------------------

/// What `gh pr view --json number,url,title,state,isDraft,headRefName` answers
/// in a worktree, or `None` when it answered something else.
///
/// `pr-linkage.md` step 2: with no argument, `gh pr view` resolves the PR for
/// the **current branch**, which is what catches a PR opened in the browser, by
/// `hub`, or by an MCP GitHub server whose stdout we never saw.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ViewedPr {
    pub number: i64,
    pub url: String,
    pub head_ref: Option<String>,
}

pub fn parse_pr_view(body: &Value) -> Option<ViewedPr> {
    let number = body.get("number").and_then(Value::as_i64)?;
    if number <= 0 {
        return None;
    }
    let url = body.get("url").and_then(Value::as_str)?.to_string();
    if url.is_empty() {
        return None;
    }
    Some(ViewedPr {
        number,
        url,
        head_ref: string_field(body, "headRefName"),
    })
}

/// Ask `gh` which PR the branch checked out in `dir` belongs to.
pub fn pr_for_cwd(dir: &std::path::Path) -> Result<Option<ViewedPr>, FetchError> {
    let output = exec::spawn(
        exec::Spawn::new(
            GH,
            &[
                "pr",
                "view",
                "--json",
                "number,url,title,state,isDraft,headRefName",
            ],
            exec::PROBE_TIMEOUT,
        )
        .in_dir(dir),
    )
    .map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    if !output.ok() {
        // "no pull requests found for branch" is the *expected* answer for a
        // branch nobody opened a PR from. It is not a failure of the poll.
        return Ok(None);
    }
    let body: Value = serde_json::from_str(&output.stdout)
        .map_err(|err| FetchError::Unparseable(err.to_string()))?;
    Ok(parse_pr_view(&body))
}

/// Step 3: match the branch against the repository's open pull requests.
///
/// The reconciliation `pr-linkage.md` keeps for the cases `gh pr view` cannot
/// answer — a fork whose head `gh` spells `owner:branch`, a worktree whose
/// HEAD is detached, a `gh` that is simply confused. `--repo` addresses the
/// repository explicitly rather than inferring it from a directory, so it works
/// from a tree whose `origin` points somewhere unexpected.
pub fn pr_for_branch(host: &str, repo: &str, branch: &str) -> Result<Option<ViewedPr>, FetchError> {
    let repo_flag = format!("{host}/{repo}");
    let output = exec::run(
        GH,
        &[
            "pr",
            "list",
            "--repo",
            &repo_flag,
            "--head",
            branch,
            "--state",
            "open",
            "--limit",
            "1",
            "--json",
            "number,url,headRefName",
        ],
        exec::PROBE_TIMEOUT,
    )
    .map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    if !output.ok() {
        return Ok(None);
    }
    let body: Value = serde_json::from_str(&output.stdout)
        .map_err(|err| FetchError::Unparseable(err.to_string()))?;
    // `gh pr list --json` answers with an array; an empty one is the ordinary
    // answer for a branch nobody opened a PR from.
    Ok(body
        .as_array()
        .and_then(|rows| rows.first())
        .and_then(parse_pr_view))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> Value {
        let raw = match name {
            "pull_requests" => include_str!("fixtures/graphql_pull_requests.json"),
            "partial_errors" => include_str!("fixtures/graphql_partial_errors.json"),
            "pr_view" => include_str!("fixtures/gh_pr_view.json"),
            "viewer" => include_str!("fixtures/graphql_viewer_pull_requests.json"),
            other => panic!("no fixture {other}"),
        };
        serde_json::from_str(raw).expect("fixture parses")
    }

    fn keys() -> Vec<PrKey> {
        vec![
            PrKey {
                owner: "jabreeflor".into(),
                name: "jabot".into(),
                number: 23,
            },
            PrKey {
                owner: "jabreeflor".into(),
                name: "globnet-sync".into(),
                number: 21,
            },
            PrKey {
                owner: "jabreeflor".into(),
                name: "jabot".into(),
                number: 19,
            },
        ]
    }

    fn found(answer: &PrAnswer) -> &PrSnapshot {
        match answer {
            PrAnswer::Found(snapshot) => snapshot,
            PrAnswer::Missing(why) => panic!("expected a snapshot, got {why}"),
        }
    }

    #[test]
    fn one_document_asks_about_every_linked_pr_and_interpolates_nothing() {
        let query = build_query(&keys());
        assert!(query.document.contains("pr0: repository(owner: $owner0"));
        assert!(query.document.contains("pr2: repository(owner: $owner2"));
        assert!(query.document.contains("fragment PrFields on PullRequest"));
        // The repository names are variables, never text in the document: a
        // repo called `x") { ... }` must not be able to write the query.
        assert!(!query.document.contains("jabreeflor"));
        assert!(!query.document.contains("globnet-sync"));
        assert_eq!(query.variables.len(), 9);
        assert_eq!(
            query.variables[0],
            ("owner0".to_string(), "jabreeflor".to_string())
        );
        assert_eq!(
            query.variables[2],
            ("number0".to_string(), "23".to_string())
        );
    }

    #[test]
    fn a_recorded_response_becomes_the_row_the_view_draws() {
        let answers = parse_response(&fixture("pull_requests"), &keys());
        assert_eq!(answers.len(), 3);

        let auth = found(&answers[0]);
        assert_eq!(auth.title, "Migrate auth to sessions");
        assert_eq!(auth.status, STATUS_OPEN);
        assert_eq!(auth.additions, 214);
        assert_eq!(auth.deletions, 96);
        assert_eq!(auth.changed_files, 3);
        assert_eq!(auth.head_ref.as_deref(), Some("jabot/t-auth"));
        assert_eq!(auth.base_ref.as_deref(), Some("main"));
        assert_eq!(auth.review_state.as_deref(), Some("changes_requested"));
        assert_eq!(auth.pr_updated_at.as_deref(), Some("2026-08-21T09:14:02Z"));
        assert_eq!(auth.check_state.as_deref(), Some(CHECKS_FAILING));

        // Both union members are drawn, and SKIPPED is not a failure.
        let checks: Vec<CheckView> = serde_json::from_str(&auth.checks_json).unwrap();
        assert_eq!(checks.len(), 4);
        assert_eq!(checks[0].label, "tests");
        assert_eq!(checks[0].state, CHECKS_FAILING);
        assert_eq!(checks[2].state, CHECKS_PASSING, "SKIPPED is not a failure");
        assert_eq!(checks[3].label, "ci/legacy");
        assert_eq!(checks[3].state, CHECKS_PASSING);
    }

    #[test]
    fn the_viewers_own_query_names_authorship_and_nothing_else() {
        let query = mine_query();
        assert!(query.document.contains("viewer {"));
        assert!(query.document.contains("states: OPEN"));
        assert!(query.document.contains(&format!("first: {MINE_LIMIT}")));
        assert!(query.document.contains("repository { nameWithOwner }"));
        assert!(query.document.contains("fragment PrFields on PullRequest"));
        // No repository, owner or search string is interpolated — there is
        // nothing in this document that came from outside the module, which is
        // why it needs no variables at all.
        assert!(query.variables.is_empty());
    }

    #[test]
    fn the_viewers_own_pull_requests_become_rows() {
        let answer = parse_mine(&fixture("viewer")).expect("the fixture names a viewer");
        assert_eq!(answer.login.as_deref(), Some("jabreeflor"));
        // Three nodes, one of them in a repository the token cannot name. A row
        // with no `owner/name` cannot be drawn or deduped, so it is dropped
        // rather than shown as a PR in nowhere.
        assert_eq!(answer.pull_requests.len(), 2);

        let own = &answer.pull_requests[0];
        assert_eq!(own.repo, "jabreeflor/jabot");
        assert_eq!(own.number, 41);
        assert_eq!(own.snapshot.status, STATUS_OPEN);
        assert_eq!(own.snapshot.check_state.as_deref(), Some(CHECKS_PASSING));
        assert_eq!(
            own.snapshot.review_state.as_deref(),
            Some("review_required")
        );
        assert_eq!(own.snapshot.additions, 612);
        assert_eq!(
            own.snapshot.url.as_deref(),
            Some("https://github.com/jabreeflor/jabot/pull/41")
        );

        // Somebody else's repository, which is the entire point of this query:
        // a PR the user wrote is theirs to see wherever it lives.
        let elsewhere = &answer.pull_requests[1];
        assert_eq!(elsewhere.repo, "someone-else/infra");
        assert_eq!(elsewhere.snapshot.status, STATUS_DRAFT);
        // No rollup at all reads as "no checks", never as "checks passed".
        assert_eq!(elsewhere.snapshot.check_state, None);
    }

    #[test]
    fn a_response_with_no_viewer_is_a_failure_and_not_an_empty_board() {
        // What a dead token looks like. Reporting it as "you have no pull
        // requests" would be a lie told to somebody who has plenty.
        let body: Value =
            serde_json::from_str(r#"{"data": null, "errors": [{"message": "Bad credentials"}]}"#)
                .unwrap();
        let err = parse_mine(&body).expect_err("no viewer is a failure");
        assert_eq!(err.reason(), "gh_failed");
        assert_eq!(err.detail(), "Bad credentials");
        // And an auth failure carries the way out of it.
        assert_eq!(
            err.remedy("github.com").as_deref(),
            Some("gh auth login --hostname github.com")
        );
    }

    #[test]
    fn a_viewer_with_nothing_open_is_an_answer() {
        let body: Value = serde_json::from_str(
            r#"{"data": {"viewer": {"login": "octocat", "pullRequests": {"nodes": []}}}}"#,
        )
        .unwrap();
        let answer = parse_mine(&body).expect("an empty board is still an answer");
        assert_eq!(answer.login.as_deref(), Some("octocat"));
        assert!(answer.pull_requests.is_empty());
    }

    #[test]
    fn a_draft_is_a_draft_and_a_merged_draft_is_merged() {
        let answers = parse_response(&fixture("pull_requests"), &keys());
        assert_eq!(found(&answers[1]).status, STATUS_DRAFT);
        assert_eq!(
            found(&answers[1]).check_state.as_deref(),
            Some(CHECKS_RUNNING)
        );
        // Merged, approved, and with no rollup at all — which must read as "no
        // checks", not as "checks passed".
        let deps = found(&answers[2]);
        assert_eq!(deps.status, STATUS_MERGED);
        assert_eq!(deps.review_state.as_deref(), Some("approved"));
        assert_eq!(deps.check_state, None);
        assert_eq!(deps.checks_json, "[]");
    }

    /// GraphQL answers `data` and `errors` at once. One repository the token
    /// cannot see must not cost the user the other nine rows.
    #[test]
    fn a_partial_failure_still_returns_the_rows_that_worked() {
        let answers = parse_response(&fixture("partial_errors"), &keys()[..2]);
        match &answers[0] {
            PrAnswer::Missing(why) => assert!(why.contains("Could not resolve"), "{why}"),
            PrAnswer::Found(_) => panic!("pr0 resolved to nothing and must be Missing"),
        }
        let retry = found(&answers[1]);
        assert_eq!(retry.status, STATUS_OPEN);
        assert_eq!(retry.review_state.as_deref(), Some("review_required"));
        // No commits at all: nothing to say about checks.
        assert_eq!(retry.check_state, None);
    }

    #[test]
    fn gh_pr_view_json_is_the_fallback_link() {
        let viewed = parse_pr_view(&fixture("pr_view")).expect("the fixture is a PR");
        assert_eq!(viewed.number, 42);
        assert_eq!(viewed.url, "https://github.com/jabreeflor/jabot/pull/42");
        assert_eq!(viewed.head_ref.as_deref(), Some("jabot/t-prs"));

        // `gh` prints `{}` for a branch with no PR; that is an answer, not a
        // pull request.
        assert_eq!(parse_pr_view(&serde_json::json!({})), None);
        assert_eq!(
            parse_pr_view(&serde_json::json!({ "number": 0, "url": "x" })),
            None
        );
    }

    #[test]
    fn a_logged_out_gh_points_at_the_login_and_a_missing_one_at_the_install() {
        let missing = FetchError::NotInstalled;
        assert_eq!(missing.reason(), "gh_missing");
        assert_eq!(
            missing.remedy("github.com").as_deref(),
            Some("brew install gh")
        );

        let logged_out = FetchError::Failed("HTTP 401: Bad credentials".into());
        assert_eq!(
            logged_out.remedy("git.corp.example.com").as_deref(),
            Some("gh auth login --hostname git.corp.example.com")
        );

        // A network blip is not something the user can fix by logging in
        // again, so it must not tell them to.
        assert_eq!(
            FetchError::Failed("dial tcp: lookup api.github.com".into()).remedy("github.com"),
            None
        );
    }

    #[test]
    fn a_check_still_running_outranks_the_green_ones() {
        let checks = vec![
            CheckView {
                label: "a".into(),
                state: CHECKS_PASSING.into(),
            },
            CheckView {
                label: "b".into(),
                state: CHECKS_RUNNING.into(),
            },
        ];
        assert_eq!(worst_of(&checks), CHECKS_RUNNING);
        let red = vec![
            CheckView {
                label: "a".into(),
                state: CHECKS_RUNNING.into(),
            },
            CheckView {
                label: "b".into(),
                state: CHECKS_FAILING.into(),
            },
        ];
        assert_eq!(worst_of(&red), CHECKS_FAILING);
    }

    #[test]
    fn gh_pr_list_answers_with_an_array_and_an_empty_one_is_an_answer() {
        let empty: Value = serde_json::json!([]);
        assert_eq!(empty.as_array().and_then(|rows| rows.first()), None);
        let one: Value = serde_json::json!([{
            "number": 8, "url": "https://github.com/o/r/pull/8", "headRefName": "jabot/t1"
        }]);
        let viewed = one
            .as_array()
            .and_then(|rows| rows.first())
            .and_then(parse_pr_view)
            .expect("one row is a PR");
        assert_eq!(viewed.number, 8);
        assert_eq!(viewed.head_ref.as_deref(), Some("jabot/t1"));
    }

    /// `gh` reads `-F name=@path` from disk, so a value an agent can influence
    /// must never reach argv with a leading `@` — that is a file exfiltrated
    /// through a request we make with the user's token. A leading `-` would
    /// let a value pose as a flag.
    #[test]
    fn a_variable_that_would_make_gh_read_a_file_is_refused() {
        assert!(!is_variable_value("@/home/user/.ssh/id_ed25519"));
        assert!(!is_variable_value("-X"));
        assert!(is_variable_value("jabreeflor"));
        assert!(is_variable_value("jabot"));
        assert!(is_variable_value("feature/some-branch"));
        assert!(!is_variable_value(""));
        assert!(!is_variable_value("owner name"));
        assert!(!is_variable_value("owner;rm -rf /"));
    }

    #[test]
    fn a_hostname_is_a_hostname_and_not_a_flag() {
        assert!(is_hostname("github.com"));
        assert!(is_hostname("git.corp.example.com"));
        assert!(is_hostname("localhost:8080"));
        assert!(!is_hostname("--version"));
        assert!(!is_hostname(""));
        assert!(!is_hostname("has space.com"));
        assert!(!is_hostname("host:notaport"));
    }

    #[test]
    fn fetch_refuses_before_it_ever_spawns_gh() {
        let query = Query {
            document: "query { viewer { login } }".into(),
            variables: vec![("owner".into(), "@/etc/passwd".into())],
        };
        // No gh on PATH in CI either way; the point is that the refusal is a
        // validation error naming the variable, not a spawn failure.
        let err = fetch("github.com", &query).expect_err("must refuse");
        let FetchError::Failed(detail) = err else {
            panic!("expected a validation refusal, got {err:?}");
        };
        assert!(detail.contains("owner"), "{detail}");
    }
}
