//! Asking GitHub about the pull requests our sessions opened.
//!
//! **One query per refresh, over `gh api graphql`.** `pr-linkage.md` settles
//! the transport: the host queries with the user's `gh` token, and `gh api
//! graphql` is "fine as the first implementation (no extra dep)". It is more
//! than fine here — the alternative is an HTTP+TLS stack in a crate that
//! deliberately has none (D-008), and letting `gh` make the request means the
//! token is never read into this process at all. `gh auth token` stays the
//! documented auth story (#16); this is the same login, one layer up.
//!
//! **Linked PRs only.** The document names each `(owner, name, number)` we have
//! a row for, under an alias. Never `repository.pullRequests(first: 30)` —
//! that would list a coworker's PRs on the user's board, and the PR view's
//! premise is that every row here was opened by a session.
//!
//! **Every value is a GraphQL variable.** Owner and repo names come out of a
//! git remote, which is a string a repository controls; interpolating one into
//! a query document is an injection. Aliases (`pr0`, `pr1`, …) are generated by
//! this module and are the only thing written into the document.
//!
//! **A partial answer is a partial success.** GraphQL answers `data` *and*
//! `errors` together: one repository the token cannot see does not invalidate
//! the other nine. Anything that parses is applied; anything that does not is
//! reported per row.

use serde_json::Value;

use super::super::repo::exec::{self, RunError};
use super::super::store::{
    PrSnapshot, CHECKS_FAILING, CHECKS_PASSING, CHECKS_RUNNING, STATUS_CLOSED, STATUS_DRAFT,
    STATUS_MERGED, STATUS_OPEN,
};

const GH: &str = "gh";

/// GitHub's own advice is serial-ish traffic; one document per refresh is one
/// request, and a slow network must not wedge the host's request thread.
const API_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(20);

/// How many PRs one document asks about. GraphQL costs points per node, and a
/// user with more linked PRs than this gets the oldest-polled ones next tick
/// rather than one enormous query that trips a secondary limit.
pub const BATCH: usize = 25;

/// The `(owner, name, number)` of one linked PR, as the query names it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrKey {
    pub owner: String,
    pub name: String,
    pub number: i64,
}

/// Why a refresh could not happen. Three cases and not one, for the reason
/// [`super::super::repo::gh::GhAuth`] gives: "GitHub is not connected" sends a
/// user who has never installed `gh` to a login page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FetchError {
    NotInstalled,
    /// `gh` ran and said no. Carries its own first line, which is the most
    /// useful sentence anyone has about the failure.
    Failed(String),
    TimedOut,
    /// `gh` succeeded and printed something that is not the answer.
    Unparseable(String),
}

impl FetchError {
    pub fn reason(&self) -> &'static str {
        match self {
            Self::NotInstalled => "gh_missing",
            Self::Failed(_) => "gh_failed",
            Self::TimedOut => "gh_timeout",
            Self::Unparseable(_) => "gh_unparseable",
        }
    }

    pub fn detail(&self) -> String {
        match self {
            Self::NotInstalled => "GitHub CLI (gh) is not installed.".to_string(),
            Self::Failed(detail) => detail.clone(),
            Self::TimedOut => format!("gh did not answer within {}s.", API_TIMEOUT.as_secs()),
            Self::Unparseable(detail) => detail.clone(),
        }
    }

    /// What the user can do about it, when there is anything.
    pub fn remedy(&self, host: &str) -> Option<String> {
        match self {
            Self::NotInstalled => Some("brew install gh".to_string()),
            // `gh` reports both a missing login and a revoked token as an HTTP
            // 401; either way the way out is the same login.
            Self::Failed(detail) if is_auth_failure(detail) => {
                Some(format!("gh auth login --hostname {host}"))
            }
            _ => None,
        }
    }
}

fn is_auth_failure(detail: &str) -> bool {
    let lower = detail.to_ascii_lowercase();
    lower.contains("401")
        || lower.contains("bad credentials")
        || lower.contains("not logged")
        || lower.contains("authentication")
}

/// The document plus the `-F name=value` arguments that fill it in.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Query {
    pub document: String,
    pub variables: Vec<(String, String)>,
}

/// Build one document covering every key, each under an alias `pr<i>`.
///
/// The fields are exactly what the prototype's row draws — title, diffstat,
/// head and base, draft flag, state, review decision — plus the checks rollup.
/// The rollup hangs off the last commit rather than off the pull request: that
/// is where GitHub's schema puts `statusCheckRollup`, and it is the path `gh pr
/// checks` itself walks. `pr-linkage.md` sketches it on `PullRequest`, which
/// does not resolve.
pub fn build_query(keys: &[PrKey]) -> Query {
    let mut params = Vec::new();
    let mut body = String::new();
    let mut variables = Vec::new();
    for (index, key) in keys.iter().enumerate() {
        params.push(format!(
            "$owner{index}: String!, $name{index}: String!, $number{index}: Int!"
        ));
        body.push_str(&format!(
            "  pr{index}: repository(owner: $owner{index}, name: $name{index}) {{ \
             pullRequest(number: $number{index}) {{ ...PrFields }} }}\n"
        ));
        variables.push((format!("owner{index}"), key.owner.clone()));
        variables.push((format!("name{index}"), key.name.clone()));
        variables.push((format!("number{index}"), key.number.to_string()));
    }
    let document = format!(
        "query({}) {{\n{}}}\n{}",
        params.join(", "),
        body,
        PR_FIELDS_FRAGMENT
    );
    Query {
        document,
        variables,
    }
}

const PR_FIELDS_FRAGMENT: &str = "fragment PrFields on PullRequest {\n\
  number title url isDraft state\n\
  additions deletions changedFiles\n\
  headRefName baseRefName reviewDecision updatedAt\n\
  commits(last: 1) { nodes { commit { statusCheckRollup {\n\
    state\n\
    contexts(first: 30) { nodes {\n\
      __typename\n\
      ... on CheckRun { name status conclusion }\n\
      ... on StatusContext { context state }\n\
    } }\n\
  } } } }\n\
}\n";

/// Run the query through `gh` and hand back the parsed JSON body.
///
/// The document goes in argv, which is safe: it contains no user data — every
/// owner, name and number travels as a `-F` variable. Nothing here ever holds a
/// token; `gh` reads its own.
pub fn fetch(host: &str, query: &Query) -> Result<Value, FetchError> {
    let mut args: Vec<String> = vec![
        "api".into(),
        "graphql".into(),
        "--hostname".into(),
        host.to_string(),
        "-f".into(),
        format!("query={}", query.document),
    ];
    for (name, value) in &query.variables {
        args.push("-F".into());
        args.push(format!("{name}={value}"));
    }
    let borrowed: Vec<&str> = args.iter().map(String::as_str).collect();
    let output = exec::run(GH, &borrowed, API_TIMEOUT).map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    // A GraphQL error comes back as exit 1 *with* a body; keep the body when
    // there is one, because "Could not resolve to a Repository" is a better
    // sentence than "gh exited 1".
    let body: Result<Value, _> = serde_json::from_str(&output.stdout);
    match body {
        Ok(value) => Ok(value),
        Err(_) if !output.ok() => Err(FetchError::Failed(first_line(&output.stderr))),
        Err(err) => Err(FetchError::Unparseable(err.to_string())),
    }
}

fn first_line(text: &str) -> String {
    text.trim()
        .lines()
        .next()
        .unwrap_or("gh failed")
        .trim()
        .to_string()
}

/// One key's answer: what GitHub said, or why it said nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PrAnswer {
    Found(Box<PrSnapshot>),
    /// The alias resolved to nothing — a repository the token cannot see, a PR
    /// that was hard-deleted, a transferred repo. Not an error for the refresh
    /// as a whole, and deliberately not a reason to unlink: a token that lost
    /// access this morning must not delete the user's board.
    Missing(String),
}

/// Split one response into one answer per key, in the order they were asked.
pub fn parse_response(body: &Value, keys: &[PrKey]) -> Vec<PrAnswer> {
    let data = body.get("data");
    let errors = body.get("errors").and_then(Value::as_array);
    keys.iter()
        .enumerate()
        .map(|(index, key)| {
            let alias = format!("pr{index}");
            let node = data
                .and_then(|data| data.get(&alias))
                .and_then(|repo| repo.get("pullRequest"));
            match node {
                Some(node) if !node.is_null() => PrAnswer::Found(Box::new(snapshot(node))),
                _ => PrAnswer::Missing(
                    error_for(errors, &alias)
                        .unwrap_or_else(|| format!("GitHub returned nothing for {}", key.number)),
                ),
            }
        })
        .collect()
}

fn error_for(errors: Option<&Vec<Value>>, alias: &str) -> Option<String> {
    let errors = errors?;
    for error in errors {
        let matches = error
            .get("path")
            .and_then(Value::as_array)
            .map(|path| path.iter().any(|part| part.as_str() == Some(alias)))
            .unwrap_or(false);
        if matches {
            return error
                .get("message")
                .and_then(Value::as_str)
                .map(str::to_string);
        }
    }
    // A document-level error (a bad token, a rate limit) has no path and
    // applies to every alias.
    errors
        .first()
        .and_then(|error| error.get("message"))
        .and_then(Value::as_str)
        .map(str::to_string)
}

/// One `PullRequest` node, mapped onto what the store and the row need.
pub fn snapshot(node: &Value) -> PrSnapshot {
    let state = node.get("state").and_then(Value::as_str).unwrap_or("OPEN");
    let draft = node
        .get("isDraft")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let contexts = rollup_contexts(node);
    let checks = checks_from_contexts(&contexts);
    PrSnapshot {
        title: node
            .get("title")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
        status: status_of(state, draft).to_string(),
        check_state: check_state(node, &checks),
        review_state: node
            .get("reviewDecision")
            .and_then(Value::as_str)
            .map(|decision| decision.to_ascii_lowercase()),
        head_ref: string_field(node, "headRefName"),
        base_ref: string_field(node, "baseRefName"),
        additions: number_field(node, "additions"),
        deletions: number_field(node, "deletions"),
        changed_files: number_field(node, "changedFiles"),
        checks_json: serde_json::to_string(&checks).unwrap_or_else(|_| "[]".to_string()),
        pr_updated_at: string_field(node, "updatedAt"),
        url: string_field(node, "url"),
    }
}

/// One row of the checks line.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct CheckView {
    pub label: String,
    /// `passing` | `running` | `failing`.
    pub state: String,
}

fn rollup_contexts(node: &Value) -> Vec<Value> {
    node.get("commits")
        .and_then(|commits| commits.get("nodes"))
        .and_then(Value::as_array)
        .and_then(|nodes| nodes.first())
        .and_then(|entry| entry.get("commit"))
        .and_then(|commit| commit.get("statusCheckRollup"))
        .and_then(|rollup| rollup.get("contexts"))
        .and_then(|contexts| contexts.get("nodes"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
}

fn rollup_state(node: &Value) -> Option<String> {
    node.get("commits")
        .and_then(|commits| commits.get("nodes"))
        .and_then(Value::as_array)
        .and_then(|nodes| nodes.first())
        .and_then(|entry| entry.get("commit"))
        .and_then(|commit| commit.get("statusCheckRollup"))
        .and_then(|rollup| rollup.get("state"))
        .and_then(Value::as_str)
        .map(str::to_string)
}

/// GitHub's `StatusState` for the whole commit, mapped to the three words the
/// row draws. Derived from the contexts when the rollup itself is absent — a
/// repository can report contexts with no rollup state, and a checks line with
/// a red tick beside "no checks" would be nonsense.
fn check_state(node: &Value, checks: &[CheckView]) -> Option<String> {
    if let Some(state) = rollup_state(node) {
        return Some(
            match state.as_str() {
                "SUCCESS" => CHECKS_PASSING,
                "PENDING" | "EXPECTED" => CHECKS_RUNNING,
                _ => CHECKS_FAILING,
            }
            .to_string(),
        );
    }
    if checks.is_empty() {
        // No checks configured. Not "checks passed" — nothing ran.
        return None;
    }
    Some(worst_of(checks).to_string())
}

/// Failing beats running beats passing: a PR with one red check is red, and one
/// still-running check is not yet reviewable.
fn worst_of(checks: &[CheckView]) -> &'static str {
    if checks.iter().any(|check| check.state == CHECKS_FAILING) {
        CHECKS_FAILING
    } else if checks.iter().any(|check| check.state == CHECKS_RUNNING) {
        CHECKS_RUNNING
    } else {
        CHECKS_PASSING
    }
}

/// `statusCheckRollup.contexts` is a union of `CheckRun` (Actions and friends)
/// and `StatusContext` (the older commit-status API). Both are drawn the same
/// way, so both are flattened here rather than in the renderer.
fn checks_from_contexts(contexts: &[Value]) -> Vec<CheckView> {
    contexts
        .iter()
        .filter_map(|context| {
            match context.get("__typename").and_then(Value::as_str) {
                Some("CheckRun") => Some(CheckView {
                    label: context
                        .get("name")
                        .and_then(Value::as_str)
                        .unwrap_or("check")
                        .to_string(),
                    state: check_run_state(context).to_string(),
                }),
                Some("StatusContext") => Some(CheckView {
                    label: context
                        .get("context")
                        .and_then(Value::as_str)
                        .unwrap_or("status")
                        .to_string(),
                    state: status_context_state(
                        context.get("state").and_then(Value::as_str).unwrap_or(""),
                    )
                    .to_string(),
                }),
                // A union member added after this was written. Skipping it
                // costs one line on the checks card; guessing at it would put a
                // green tick under a check nobody has looked at.
                _ => None,
            }
        })
        .collect()
}

/// A `CheckRun` reports a lifecycle *and* an outcome, and only the pair means
/// anything: `conclusion: null` on a completed run is a run still finishing,
/// and `SKIPPED` is not a failure.
fn check_run_state(context: &Value) -> &'static str {
    let status = context
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or("QUEUED");
    if status != "COMPLETED" {
        return CHECKS_RUNNING;
    }
    match context.get("conclusion").and_then(Value::as_str) {
        Some("SUCCESS") | Some("NEUTRAL") | Some("SKIPPED") => CHECKS_PASSING,
        Some(_) => CHECKS_FAILING,
        None => CHECKS_RUNNING,
    }
}

fn status_context_state(state: &str) -> &'static str {
    match state {
        "SUCCESS" => CHECKS_PASSING,
        "PENDING" | "EXPECTED" => CHECKS_RUNNING,
        _ => CHECKS_FAILING,
    }
}

/// `state` + `isDraft` collapse into the one word `thread_prs.status` holds.
/// A merged PR that was opened as a draft is merged, not a draft.
fn status_of(state: &str, draft: bool) -> &'static str {
    match state {
        "MERGED" => STATUS_MERGED,
        "CLOSED" => STATUS_CLOSED,
        _ if draft => STATUS_DRAFT,
        _ => STATUS_OPEN,
    }
}

fn string_field(node: &Value, field: &str) -> Option<String> {
    node.get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

fn number_field(node: &Value, field: &str) -> i64 {
    node.get(field).and_then(Value::as_i64).unwrap_or(0)
}

// ---- `gh pr view`, the post-turn fallback ------------------------------

/// What `gh pr view --json number,url,title,state,isDraft,headRefName` answers
/// in a worktree, or `None` when it answered something else.
///
/// `pr-linkage.md` step 2: with no argument, `gh pr view` resolves the PR for
/// the **current branch**, which is what catches a PR opened in the browser, by
/// `hub`, or by an MCP GitHub server whose stdout we never saw.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ViewedPr {
    pub number: i64,
    pub url: String,
    pub head_ref: Option<String>,
}

pub fn parse_pr_view(body: &Value) -> Option<ViewedPr> {
    let number = body.get("number").and_then(Value::as_i64)?;
    if number <= 0 {
        return None;
    }
    let url = body.get("url").and_then(Value::as_str)?.to_string();
    if url.is_empty() {
        return None;
    }
    Some(ViewedPr {
        number,
        url,
        head_ref: string_field(body, "headRefName"),
    })
}

/// Ask `gh` which PR the branch checked out in `dir` belongs to.
pub fn pr_for_cwd(dir: &std::path::Path) -> Result<Option<ViewedPr>, FetchError> {
    let output = exec::spawn(
        exec::Spawn::new(
            GH,
            &[
                "pr",
                "view",
                "--json",
                "number,url,title,state,isDraft,headRefName",
            ],
            exec::PROBE_TIMEOUT,
        )
        .in_dir(dir),
    )
    .map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    if !output.ok() {
        // "no pull requests found for branch" is the *expected* answer for a
        // branch nobody opened a PR from. It is not a failure of the poll.
        return Ok(None);
    }
    let body: Value = serde_json::from_str(&output.stdout)
        .map_err(|err| FetchError::Unparseable(err.to_string()))?;
    Ok(parse_pr_view(&body))
}

/// Step 3: match the branch against the repository's open pull requests.
///
/// The reconciliation `pr-linkage.md` keeps for the cases `gh pr view` cannot
/// answer — a fork whose head `gh` spells `owner:branch`, a worktree whose
/// HEAD is detached, a `gh` that is simply confused. `--repo` addresses the
/// repository explicitly rather than inferring it from a directory, so it works
/// from a tree whose `origin` points somewhere unexpected.
pub fn pr_for_branch(host: &str, repo: &str, branch: &str) -> Result<Option<ViewedPr>, FetchError> {
    let repo_flag = format!("{host}/{repo}");
    let output = exec::run(
        GH,
        &[
            "pr",
            "list",
            "--repo",
            &repo_flag,
            "--head",
            branch,
            "--state",
            "open",
            "--limit",
            "1",
            "--json",
            "number,url,headRefName",
        ],
        exec::PROBE_TIMEOUT,
    )
    .map_err(|err| match err {
        RunError::NotInstalled(_) => FetchError::NotInstalled,
        RunError::TimedOut => FetchError::TimedOut,
        RunError::Failed(detail) => FetchError::Failed(detail),
    })?;
    if !output.ok() {
        return Ok(None);
    }
    let body: Value = serde_json::from_str(&output.stdout)
        .map_err(|err| FetchError::Unparseable(err.to_string()))?;
    // `gh pr list --json` answers with an array; an empty one is the ordinary
    // answer for a branch nobody opened a PR from.
    Ok(body
        .as_array()
        .and_then(|rows| rows.first())
        .and_then(parse_pr_view))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> Value {
        let raw = match name {
            "pull_requests" => include_str!("fixtures/graphql_pull_requests.json"),
            "partial_errors" => include_str!("fixtures/graphql_partial_errors.json"),
            "pr_view" => include_str!("fixtures/gh_pr_view.json"),
            other => panic!("no fixture {other}"),
        };
        serde_json::from_str(raw).expect("fixture parses")
    }

    fn keys() -> Vec<PrKey> {
        vec![
            PrKey {
                owner: "jabreeflor".into(),
                name: "jabot".into(),
                number: 23,
            },
            PrKey {
                owner: "jabreeflor".into(),
                name: "globnet-sync".into(),
                number: 21,
            },
            PrKey {
                owner: "jabreeflor".into(),
                name: "jabot".into(),
                number: 19,
            },
        ]
    }

    fn found(answer: &PrAnswer) -> &PrSnapshot {
        match answer {
            PrAnswer::Found(snapshot) => snapshot,
            PrAnswer::Missing(why) => panic!("expected a snapshot, got {why}"),
        }
    }

    #[test]
    fn one_document_asks_about_every_linked_pr_and_interpolates_nothing() {
        let query = build_query(&keys());
        assert!(query.document.contains("pr0: repository(owner: $owner0"));
        assert!(query.document.contains("pr2: repository(owner: $owner2"));
        assert!(query.document.contains("fragment PrFields on PullRequest"));
        // The repository names are variables, never text in the document: a
        // repo called `x") { ... }` must not be able to write the query.
        assert!(!query.document.contains("jabreeflor"));
        assert!(!query.document.contains("globnet-sync"));
        assert_eq!(query.variables.len(), 9);
        assert_eq!(
            query.variables[0],
            ("owner0".to_string(), "jabreeflor".to_string())
        );
        assert_eq!(
            query.variables[2],
            ("number0".to_string(), "23".to_string())
        );
    }

    #[test]
    fn a_recorded_response_becomes_the_row_the_view_draws() {
        let answers = parse_response(&fixture("pull_requests"), &keys());
        assert_eq!(answers.len(), 3);

        let auth = found(&answers[0]);
        assert_eq!(auth.title, "Migrate auth to sessions");
        assert_eq!(auth.status, STATUS_OPEN);
        assert_eq!(auth.additions, 214);
        assert_eq!(auth.deletions, 96);
        assert_eq!(auth.changed_files, 3);
        assert_eq!(auth.head_ref.as_deref(), Some("jabot/t-auth"));
        assert_eq!(auth.base_ref.as_deref(), Some("main"));
        assert_eq!(auth.review_state.as_deref(), Some("changes_requested"));
        assert_eq!(auth.pr_updated_at.as_deref(), Some("2026-08-21T09:14:02Z"));
        assert_eq!(auth.check_state.as_deref(), Some(CHECKS_FAILING));

        // Both union members are drawn, and SKIPPED is not a failure.
        let checks: Vec<CheckView> = serde_json::from_str(&auth.checks_json).unwrap();
        assert_eq!(checks.len(), 4);
        assert_eq!(checks[0].label, "tests");
        assert_eq!(checks[0].state, CHECKS_FAILING);
        assert_eq!(checks[2].state, CHECKS_PASSING, "SKIPPED is not a failure");
        assert_eq!(checks[3].label, "ci/legacy");
        assert_eq!(checks[3].state, CHECKS_PASSING);
    }

    #[test]
    fn a_draft_is_a_draft_and_a_merged_draft_is_merged() {
        let answers = parse_response(&fixture("pull_requests"), &keys());
        assert_eq!(found(&answers[1]).status, STATUS_DRAFT);
        assert_eq!(
            found(&answers[1]).check_state.as_deref(),
            Some(CHECKS_RUNNING)
        );
        // Merged, approved, and with no rollup at all — which must read as "no
        // checks", not as "checks passed".
        let deps = found(&answers[2]);
        assert_eq!(deps.status, STATUS_MERGED);
        assert_eq!(deps.review_state.as_deref(), Some("approved"));
        assert_eq!(deps.check_state, None);
        assert_eq!(deps.checks_json, "[]");
    }

    /// GraphQL answers `data` and `errors` at once. One repository the token
    /// cannot see must not cost the user the other nine rows.
    #[test]
    fn a_partial_failure_still_returns_the_rows_that_worked() {
        let answers = parse_response(&fixture("partial_errors"), &keys()[..2]);
        match &answers[0] {
            PrAnswer::Missing(why) => assert!(why.contains("Could not resolve"), "{why}"),
            PrAnswer::Found(_) => panic!("pr0 resolved to nothing and must be Missing"),
        }
        let retry = found(&answers[1]);
        assert_eq!(retry.status, STATUS_OPEN);
        assert_eq!(retry.review_state.as_deref(), Some("review_required"));
        // No commits at all: nothing to say about checks.
        assert_eq!(retry.check_state, None);
    }

    #[test]
    fn gh_pr_view_json_is_the_fallback_link() {
        let viewed = parse_pr_view(&fixture("pr_view")).expect("the fixture is a PR");
        assert_eq!(viewed.number, 42);
        assert_eq!(viewed.url, "https://github.com/jabreeflor/jabot/pull/42");
        assert_eq!(viewed.head_ref.as_deref(), Some("jabot/t-prs"));

        // `gh` prints `{}` for a branch with no PR; that is an answer, not a
        // pull request.
        assert_eq!(parse_pr_view(&serde_json::json!({})), None);
        assert_eq!(
            parse_pr_view(&serde_json::json!({ "number": 0, "url": "x" })),
            None
        );
    }

    #[test]
    fn a_logged_out_gh_points_at_the_login_and_a_missing_one_at_the_install() {
        let missing = FetchError::NotInstalled;
        assert_eq!(missing.reason(), "gh_missing");
        assert_eq!(
            missing.remedy("github.com").as_deref(),
            Some("brew install gh")
        );

        let logged_out = FetchError::Failed("HTTP 401: Bad credentials".into());
        assert_eq!(
            logged_out.remedy("git.corp.example.com").as_deref(),
            Some("gh auth login --hostname git.corp.example.com")
        );

        // A network blip is not something the user can fix by logging in
        // again, so it must not tell them to.
        assert_eq!(
            FetchError::Failed("dial tcp: lookup api.github.com".into()).remedy("github.com"),
            None
        );
    }

    #[test]
    fn a_check_still_running_outranks_the_green_ones() {
        let checks = vec![
            CheckView {
                label: "a".into(),
                state: CHECKS_PASSING.into(),
            },
            CheckView {
                label: "b".into(),
                state: CHECKS_RUNNING.into(),
            },
        ];
        assert_eq!(worst_of(&checks), CHECKS_RUNNING);
        let red = vec![
            CheckView {
                label: "a".into(),
                state: CHECKS_RUNNING.into(),
            },
            CheckView {
                label: "b".into(),
                state: CHECKS_FAILING.into(),
            },
        ];
        assert_eq!(worst_of(&red), CHECKS_FAILING);
    }

    #[test]
    fn gh_pr_list_answers_with_an_array_and_an_empty_one_is_an_answer() {
        let empty: Value = serde_json::json!([]);
        assert_eq!(empty.as_array().and_then(|rows| rows.first()), None);
        let one: Value = serde_json::json!([{
            "number": 8, "url": "https://github.com/o/r/pull/8", "headRefName": "jabot/t1"
        }]);
        let viewed = one
            .as_array()
            .and_then(|rows| rows.first())
            .and_then(parse_pr_view)
            .expect("one row is a PR");
        assert_eq!(viewed.number, 8);
        assert_eq!(viewed.head_ref.as_deref(), Some("jabot/t1"));
    }
}
