//! Per-bot memory: two markdown files in a directory the bot owns (#17).
//!
//! There is no cloud memory store and no vector database. A bot's memory is
//! `MEMORY.md` in its own directory, which is also the `cwd` a worker's
//! standing thread runs in (decision #6) — so the agent reads and writes it
//! with the ordinary file tools it already has, under the ordinary permission
//! prompts, and the user can open it in any editor.
//!
//! Two rules, and they pull in opposite directions on purpose.
//!
//! **`instructions.md` is derived.** It is the bot record's `instructions`
//! field written to disk so the session can read the persona. The host owns
//! it and rewrites it whenever the record changes; the file says so.
//!
//! **`MEMORY.md` is the bot's, and the host never touches it after creating
//! it.** "No unattended memory writes without review" means the host must not
//! be in the business of appending to a bot's notes behind the user's back —
//! anything that lands there landed through a session the user could see, and
//! through a permission prompt if the harness asked for one.
//!
//! The directory is also the isolation floor from decision #6 made concrete:
//! one directory per bot id, never shared, and never a place a credential is
//! written. Credentials are in the keychain; this is markdown.

use std::path::{Path, PathBuf};

/// The persona, mirrored from the record. Regenerated, never merged.
pub const INSTRUCTIONS_FILE: &str = "instructions.md";
/// The bot's own notes. Created once, then left alone by the host.
pub const MEMORY_FILE: &str = "MEMORY.md";

/// Where a bot's directory goes under the app data dir. One level of nesting
/// so `bots/` stays browsable next to `adapter-logs/` and `custom_harnesses/`.
pub fn dir_for(data_dir: &Path, bot_id: &str) -> PathBuf {
    data_dir.join("bots").join(bot_id)
}

/// Create the directory and its two files, and refresh the derived one.
///
/// Idempotent, and quiet about it: `instructions.md` is only written when the
/// bytes would change, so listing the crew does not churn mtimes, and
/// `MEMORY.md` is only written when it does not exist at all.
pub fn ensure(dir: &Path, bot_name: &str, instructions: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;

    let wanted = instructions_markdown(bot_name, instructions);
    let instructions_path = dir.join(INSTRUCTIONS_FILE);
    if std::fs::read_to_string(&instructions_path).ok() != Some(wanted.clone()) {
        std::fs::write(&instructions_path, &wanted)?;
    }

    let memory_path = dir.join(MEMORY_FILE);
    if !memory_path.exists() {
        std::fs::write(&memory_path, memory_seed(bot_name))?;
    }
    Ok(())
}

/// The derived file's contents. The header is load-bearing: without it the
/// first person to edit this file by hand loses their edit on the next save
/// and has no way of knowing why.
fn instructions_markdown(bot_name: &str, instructions: &str) -> String {
    let body = instructions.trim();
    let body = if body.is_empty() {
        "_No instructions yet._"
    } else {
        body
    };
    format!(
        "# {bot_name}\n\n\
         <!-- Generated by JaBot from this bot's record. Edit the bot in the\n\
         crew editor; changes made here are overwritten on the next save. -->\n\n\
         {body}\n"
    )
}

/// The starter `MEMORY.md`. Deliberately close to empty — the host has nothing
/// to say about what this bot has learned, and pre-filling it with invented
/// context would be the first unattended memory write.
fn memory_seed(bot_name: &str) -> String {
    format!(
        "# {bot_name} — memory\n\n\
         What this bot has learned and should carry between sessions.\n\
         It writes here during a session; you can edit or clear it any time.\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensure_creates_both_files_and_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let bot = dir.path().join("bots").join("writer");

        ensure(&bot, "Writer", "Draft in my voice.").unwrap();
        let instructions = std::fs::read_to_string(bot.join(INSTRUCTIONS_FILE)).unwrap();
        assert!(instructions.contains("Draft in my voice."));
        assert!(instructions.contains("# Writer"));
        assert!(std::fs::read_to_string(bot.join(MEMORY_FILE))
            .unwrap()
            .contains("Writer"));

        ensure(&bot, "Writer", "Draft in my voice.").unwrap();
        assert_eq!(
            std::fs::read_to_string(bot.join(INSTRUCTIONS_FILE)).unwrap(),
            instructions
        );
    }

    /// The rule the module exists for: the persona is the host's file, the
    /// notes are the bot's. A save may rewrite the first and must never touch
    /// the second.
    #[test]
    fn a_saved_edit_rewrites_instructions_and_leaves_memory_alone() {
        let dir = tempfile::tempdir().unwrap();
        let bot = dir.path().join("bots").join("writer");
        ensure(&bot, "Writer", "Draft in my voice.").unwrap();

        let learned = "# Writer — memory\n\nJabree hates exclamation marks.\n";
        std::fs::write(bot.join(MEMORY_FILE), learned).unwrap();

        ensure(&bot, "Ghostwriter", "Short and plain.").unwrap();

        let instructions = std::fs::read_to_string(bot.join(INSTRUCTIONS_FILE)).unwrap();
        assert!(instructions.contains("Short and plain."));
        assert!(!instructions.contains("Draft in my voice."));
        assert_eq!(
            std::fs::read_to_string(bot.join(MEMORY_FILE)).unwrap(),
            learned,
            "the host must never overwrite what a bot has learned"
        );
    }

    #[test]
    fn an_empty_persona_still_produces_a_readable_file() {
        let dir = tempfile::tempdir().unwrap();
        let bot = dir.path().join("bots").join("blank");
        ensure(&bot, "Blank", "   ").unwrap();
        assert!(std::fs::read_to_string(bot.join(INSTRUCTIONS_FILE))
            .unwrap()
            .contains("_No instructions yet._"));
    }

    #[test]
    fn two_bots_never_share_a_directory() {
        let data = Path::new("/tmp/jabot-data");
        assert_ne!(dir_for(data, "writer"), dir_for(data, "rsrch"));
        assert!(dir_for(data, "writer").ends_with("bots/writer"));
    }
}
