#!/usr/bin/env bash
#
# Type-check and lint src-tauri/src/notify/mac.rs against the real macOS
# target, from Linux, with no Mac.
#
#   ./scripts/check-mac-notify.sh
#
# WHY THIS EXISTS
#
# `src-tauri/src/notify/mod.rs` gates `mod mac;` behind
# `#[cfg(target_os = "macos")]`, so nothing in ./scripts/verify.sh — the repo's
# only gate, which runs on Linux — ever compiles or lints that file. CI's
# `bundle` job is the only thing that would, and it does not run on pull
# requests. So `mac.rs` can rot silently until somebody builds on a Mac, which
# is the worst possible moment to find out.
#
# WHY A SCRATCH CRATE AND NOT `cargo clippy --target x86_64-apple-darwin`
#
# Cross-checking the whole crate does not work: `objc2-exception-helper`, pulled
# in through tauri, has a `cc` build script that needs an Apple toolchain and
# fails on Linux. The scratch crate avoids it because nothing in `notify` uses
# ObjC exceptions — it depends only on the four objc2 crates `mac.rs` actually
# names. (Recorded as D-019, now issue #72.)
#
# NETWORK. The scratch crate resolves and downloads the macOS-only half of the
# dependency graph, which a Linux build has never fetched. That is why this is
# its own script and an opt-in `--check-mac` stage rather than part of the
# default offline path.
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT=$(pwd)
MANIFEST="$ROOT/src-tauri/Cargo.toml"
NOTIFY="$ROOT/src-tauri/src/notify"
TARGET=x86_64-apple-darwin

fail() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# The target, or the exact line that installs it.
#
# Skipping silently is the one thing this must not do: a check that quietly
# does nothing on the machine that needed it is worse than no check, because
# the log still says the stage ran.
# ---------------------------------------------------------------------------
command -v rustup >/dev/null 2>&1 ||
  fail "rustup not found; this check needs it to supply the $TARGET std"
if ! rustup target list --installed | grep -qx "$TARGET"; then
  fail "the $TARGET std is not installed. Run:

    rustup target add $TARGET"
fi

# ---------------------------------------------------------------------------
# The stub's contract, checked rather than assumed.
#
# The scratch crate supplies a fake `crate::host` because that is the only
# thing `notify/` imports from the rest of the app. If a later change adds
# another `crate::` path, the stub silently stops matching and clippy fails
# with an unresolved-import error that reads like a broken script rather than
# like "this file has a new dependency". So name the mismatch here.
# ---------------------------------------------------------------------------
ALLOWED='use crate::host::{INBOX_EVENT, INBOX_RESURFACE};'
unexpected=$(grep -hn 'crate::' "$NOTIFY"/*.rs | grep -vF "$ALLOWED" || true)
if [[ -n "$unexpected" ]]; then
  fail "notify/ imports something the stub in this script does not provide:

$unexpected

Add it to the \`pub mod host\` stub below, or the check will fail with an
unresolved-path error that says nothing about why."
fi

# ---------------------------------------------------------------------------
# The version requirements, read out of the real manifest.
#
# Hardcoding them would let the scratch crate fork the objc2 graph the app
# pins, and then this check would be lint against a different library than the
# one that ships.
# ---------------------------------------------------------------------------
req() {
  local crate="$1" line
  line=$(grep -E "^${crate} = " "$MANIFEST" | head -1) ||
    fail "no requirement for '$crate' in src-tauri/Cargo.toml"
  [[ -n "$line" ]] || fail "no requirement for '$crate' in src-tauri/Cargo.toml"
  printf '%s\n' "$line"
}

SCRATCH=$(mktemp -d)
trap 'rm -rf "$SCRATCH"' EXIT
mkdir -p "$SCRATCH/src"

{
  cat <<'HEAD'
[package]
name = "mac-notify-cross-check"
version = "0.0.0"
edition = "2021"

# Its own workspace, so running this from inside a checkout does not get the
# scratch crate adopted by anything.
[workspace]

[dependencies]
HEAD
  req serde
  req serde_json
  printf '\n[target.%s.dependencies]\n' "'cfg(target_os = \"macos\")'"
  req objc2
  req objc2-foundation
  req objc2-user-notifications
  req block2
} > "$SCRATCH/Cargo.toml"

cat > "$SCRATCH/src/lib.rs" <<RS
//! Generated by scripts/check-mac-notify.sh. Do not edit.

/// The only thing \`notify/\` imports from the app. Values are irrelevant —
/// what is being checked is that \`mac.rs\` compiles and lints, not what it
/// sends.
pub mod host {
    pub const INBOX_EVENT: &str = "inbox/event";
    pub const INBOX_RESURFACE: &str = "inbox/resurface";
}

#[path = "$NOTIFY/mod.rs"]
pub mod notify;
RS

printf 'cross-checking %s against %s\n' "src-tauri/src/notify/" "$TARGET"
cargo clippy \
  --manifest-path "$SCRATCH/Cargo.toml" \
  --target "$TARGET" \
  --all-targets \
  -- -D warnings ||
  fail "src-tauri/src/notify/ does not build clean for $TARGET"

printf '\033[32mnotify/ is clean for %s\033[0m\n' "$TARGET"
